### ISSUE TITLE
Circuit diagram link dead

### ISSUE THREAD

**Issue by Nirach-N09** [speeddragon/Arduino-CarSensorDashboard#1]
Just been reading through your repo and noticed that (probably owing to changes out of your control), the diagram link is dead.

I'd be interested in seeing it if you have anything still to hand!

**Comment by speeddragon** [comment]
I didn't take a picture of the diagram, but should be simple, because each sensor is connected via a voltage divider. I will try to check if I can draw another diagram with the values used for the resistors.

**Comment by Nirach-N09** [comment]
That'd be super cool, I appreciate it!

**Comment by speeddragon** [comment]
I've added a little diagram, showing how to wire one of the senders and some text explaining the difference for the other ones. I don't work with electronic, this is just a hobby, so if something doesn't make sense feel free to ask here or in other forums to have an opinion of a more expert person.
